export const seedTasks = [
  {
    id: "BEN-1042",
    title: "Validar fatura mensal da Unimed",
    status: "Em andamento",
    priority: "Crítica",
    owner: "Larissa",
    ownerEmail: "larissa@beneficioscowork.com",
    supplier: "Unimed",
    competence: "03/2026",
    dueDate: "2026-03-27",
    category: "Fatura",
    type: "Rotina",
    unit: "Campinas",
    brand: "Matriz",
    notes: "Conferir vidas, custo e divergências.",
  },
  {
    id: "BEN-1043",
    title: "Cobrar boleto pendente do vale-refeição",
    status: "Aguardando retorno",
    priority: "Alta",
    owner: "Paulo",
    ownerEmail: "paulo@beneficioscowork.com",
    supplier: "Flash",
    competence: "03/2026",
    dueDate: "2026-03-26",
    category: "Financeiro",
    type: "Avulsa",
    unit: "São Paulo",
    brand: "Operações",
    notes: "Pendência aberta com financeiro e fornecedor.",
  },
  {
    id: "BEN-1044",
    title: "Aprovar comunicação de reajuste",
    status: "Aguardando aprovação",
    priority: "Alta",
    owner: "Renata",
    ownerEmail: "renata@beneficioscowork.com",
    supplier: "Bradesco Saúde",
    competence: "03/2026",
    dueDate: "2026-03-28",
    category: "Comunicação",
    type: "Avulsa",
    unit: "Remoto",
    brand: "Corporativo",
    notes: "Texto final aguarda validação da liderança.",
  },
  {
    id: "BEN-1045",
    title: "Revisar elegibilidade da unidade Campinas",
    status: "Não iniciada",
    priority: "Média",
    owner: "Larissa",
    ownerEmail: "larissa@beneficioscowork.com",
    supplier: "Alice",
    competence: "03/2026",
    dueDate: "2026-03-29",
    category: "Elegibilidade",
    type: "Rotina",
    unit: "Campinas",
    brand: "Matriz",
    notes: "Cruzar inclusões e exclusões com base do RH.",
  },
  {
    id: "BEN-1046",
    title: "Anexar evidências do fechamento odontológico",
    status: "Concluída",
    priority: "Baixa",
    owner: "Paulo",
    ownerEmail: "paulo@beneficioscowork.com",
    supplier: "SulAmérica",
    competence: "03/2026",
    dueDate: "2026-03-24",
    category: "Fechamento",
    type: "Rotina",
    unit: "São Paulo",
    brand: "Operações",
    notes: "Arquivos enviados para auditoria interna.",
  },
  {
    id: "BEN-1047",
    title: "Corrigir divergência de coparticipação PJ",
    status: "Bloqueada",
    priority: "Crítica",
    owner: "Renata",
    ownerEmail: "renata@beneficioscowork.com",
    supplier: "Unimed",
    competence: "03/2026",
    dueDate: "2026-03-25",
    category: "Coparticipação",
    type: "Avulsa",
    unit: "Remoto",
    brand: "Corporativo",
    notes: "Aguardando retorno da operadora sobre o cálculo.",
  },
];

export const seedMembers = [
  { full_name: "Larissa", email: "larissa@beneficioscowork.com", role: "analyst" },
  { full_name: "Paulo", email: "paulo@beneficioscowork.com", role: "analyst" },
  { full_name: "Renata", email: "renata@beneficioscowork.com", role: "supervisor" },
];

export const seedTemplates = [
  {
    id: 1,
    name: "Fechamento mensal - plano de saúde",
    rule: "Todo início de competência",
    sla: "24 horas",
  },
  {
    id: 2,
    name: "Conferência de boleto - benefício flexível",
    rule: "Semanal",
    sla: "8 horas",
  },
  {
    id: 3,
    name: "Revisão de elegibilidade por competência",
    rule: "Mensal",
    sla: "16 horas",
  },
];

export const seedChecklist = [
  "Receber arquivo do fornecedor",
  "Validar vidas e movimentações",
  "Comparar custo vs competência anterior",
  "Registrar divergências",
  "Anexar evidências",
  "Sinalizar financeiro",
  "Concluir rotina",
];

export const seedWikiPages = [
  { title: "POP - Fechamento mensal de saúde", category: "POP" },
  { title: "Fluxo de exceção - inclusão retroativa", category: "Exceções" },
  { title: "Regras por fornecedor - Flash", category: "Fornecedor" },
  { title: "FAQ interno - coparticipação", category: "FAQ" },
];

export const seedDocuments = [
  {
    title: "POP - Fechamento mensal de saúde",
    category: "POP",
    content: "Passo a passo do fechamento mensal do plano de saúde.",
  },
  {
    title: "Fluxo de exceção - inclusão retroativa",
    category: "Exceções",
    content: "Procedimento para tratar inclusões fora da janela padrão.",
  },
  {
    title: "Regras por fornecedor - Flash",
    category: "Fornecedor",
    content: "Regras operacionais e pontos de contato do fornecedor Flash.",
  },
];

export const seedActivity = [
  "Larissa alterou BEN-1042 para Em andamento",
  "Paulo anexou evidência financeira em BEN-1043",
  "Renata solicitou aprovação para BEN-1044",
  "Sistema gerou rotinas da competência 03/2026",
];
